name: DriftFX Build

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
 
jobs:
  build-natives:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev
      if: runner.os == 'Linux'
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11
    - uses: actions/checkout@v3
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4
    - name: Build
      run: gradle -i :org.eclipse.fx.drift.native:publish
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: native-repo
        path: native-repo
        
  build-java:
    needs: build-natives
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: setup-java-8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8
        java-package: jdk+fx
    - id: setup-java-11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11
        java-package: jdk
    - name: Download natives
      uses: actions/download-artifact@v3
      with:
        name: native-repo
        path: native-repo
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4
    - name: Build Jar
      run: gradle -i buildMultireleaseJar
      env:
        JAVA_HOME_8: ${{ steps.setup-java-8.outputs.path }}
        JAVA_HOME_11: ${{ steps.setup-java-11.outputs.path }}
    - uses: actions/upload-artifact@v3
      with:
        name: artifact-unsigned
        path: build/libs/org.eclipse.fx.drift.jar

