name: DriftFX Build

on: [push]

jobs:
  build-natives:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/checkout@v2
    - uses: eskatos/gradle-command-action@v1
      with:
        build-root-directory: native-gradle
        wrapper-directory: native-gradle
        arguments: publish
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v1
      with:
        name: native-repo
        path: native-repo
        
