name: DriftFX Build

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build-natives:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev
      if: runner.os == 'Linux'
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11
        #architecture: arm64
    - uses: actions/checkout@v2
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: -i :org.eclipse.fx.drift.native:publish -Pforce-aarch64
    - uses: eskatos/gradle-command-action@v1
    - name: move binaries
      shell: bash
      run: |
        mv ./native-repo/org/eclipse/fx/drift/driftfx ./native-repo/org/eclipse/fx/drift/driftfx_aarch64
        mv ./native-repo/org/eclipse/fx/drift/driftfx_debug_macos ./native-repo/org/eclipse/fx/drift/driftfx_debug_macos_aarch64
        mv ./native-repo/org/eclipse/fx/drift/driftfx_release_macos ./native-repo/org/eclipse/fx/drift/driftfx_release_macos_aarch64
      with:
        arguments: -i :org.eclipse.fx.drift.native:publish
    - uses: actions/upload-artifact@v1
      with:
        name: native-repo
        path: native-repo
        
  build-java:
    needs: build-natives
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: Store Java 1.8 Home
      run: echo "JAVA_HOME_8=${JAVA_HOME}" >> $GITHUB_ENV
    - name: Setup Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
    - name: Store Java 11 Home
      run: echo "JAVA_HOME_11=${JAVA_HOME}" >> $GITHUB_ENV
    - name: Download natives
      uses: actions/download-artifact@v1
      with:
        name: native-repo
        path: native-repo
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: -i buildMultireleaseJar
    - uses: actions/upload-artifact@v1
      with:
        name: artifact-unsigned
        path: build/libs/org.eclipse.fx.drift.jar
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: notifyJenkins
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        JENKINS_ACCESS_TOKEN: ${{ secrets.JENKINS_ACCESS_TOKEN }}
