name: DriftFX Deploy
on:
  workflow_run:
    workflows: ["DriftFX Build"]
    types:
      - completed
    branches:
      - master
    tags:
      - 'v*'

jobs:
  notifyJenkins:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: Store Java 1.8 Home
      run: echo "JAVA_HOME_8=${JAVA_HOME}" >> $GITHUB_ENV
    - name: Setup Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
    - name: Store Java 11 Home
      run: echo "JAVA_HOME_11=${JAVA_HOME}" >> $GITHUB_ENV
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: notifyJenkins
      env:
        BUILD_RUN_ID: ${{ github.event.workflow_run.id }}
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JENKINS_ACCESS_TOKEN: ${{ secrets.JENKINS_ACCESS_TOKEN }}